-- =============================================================================
-- ⚠ DEPRECATED — DO NOT USE AS SOURCE OF SCHEMA TRUTH
-- Canonical schema + RLS + gc_commerce + catalog_v2 live under `supabase/migrations/`.
-- Apply with Supabase CLI (`supabase db push` / linked project) or your migration runner.
-- This file is retained only as historical reference (pre–UUID inventory / pre–gc_commerce carts).
-- =============================================================================
-- GLOVECUBS CORE E-COMMERCE TABLES (LEGACY SNAPSHOT)
-- =============================================================================

-- Users table (if not exists)
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_name TEXT,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT,
  contact_name TEXT,
  phone TEXT,
  address TEXT,
  city TEXT,
  state TEXT,
  zip TEXT,
  cases_or_pallets TEXT,
  allow_free_upgrades BOOLEAN DEFAULT false,
  payment_terms TEXT DEFAULT 'credit_card',
  is_approved INT DEFAULT 0,
  discount_tier TEXT DEFAULT 'standard',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Products table (if not exists)
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  sku TEXT UNIQUE,
  slug TEXT UNIQUE,
  mpn TEXT,
  upc TEXT,
  name TEXT NOT NULL,
  title TEXT,
  brand TEXT,
  manufacturer TEXT,
  material TEXT,
  glove_type TEXT,
  color TEXT,
  grade TEXT,
  texture TEXT,
  powder_free BOOLEAN,
  latex_free BOOLEAN,
  thickness_mil NUMERIC(5,2),
  sizes TEXT[],
  images TEXT[],
  description TEXT,
  features TEXT[],
  category TEXT,
  certifications TEXT[],
  attributes JSONB DEFAULT '{}'::jsonb,
  cost NUMERIC(12,2),
  sell_price NUMERIC(12,2),
  units_per_case INT,
  boxes_per_case INT,
  units_per_box INT,
  is_active BOOLEAN DEFAULT true,
  source_url TEXT,
  import_confidence NUMERIC(4,3),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Manufacturers
CREATE TABLE IF NOT EXISTS public.manufacturers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL UNIQUE,
  website TEXT,
  logo_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Companies
CREATE TABLE IF NOT EXISTS public.companies (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  discount_tier TEXT DEFAULT 'standard',
  payment_terms TEXT DEFAULT 'credit_card',
  credit_limit NUMERIC(12,2),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Orders
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  order_number TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'pending',
  payment_method TEXT,
  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount NUMERIC(12,2) NOT NULL DEFAULT 0,
  shipping NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax NUMERIC(12,2) NOT NULL DEFAULT 0,
  total NUMERIC(12,2) NOT NULL DEFAULT 0,
  shipping_address JSONB,
  ship_to_id BIGINT,
  notes TEXT,
  stripe_payment_intent_id TEXT,
  tracking_number TEXT,
  tracking_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.order_items (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  size TEXT,
  unit_price NUMERIC(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_orders_user ON public.orders (user_id);
CREATE INDEX IF NOT EXISTS idx_order_items_order ON public.order_items (order_id);

-- Carts
CREATE TABLE IF NOT EXISTS public.carts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cart_key TEXT NOT NULL UNIQUE,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_carts_key ON public.carts (cart_key);

-- Inventory
CREATE TABLE IF NOT EXISTS public.inventory (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  quantity_on_hand INT NOT NULL DEFAULT 0,
  reorder_point INT DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(product_id)
);

-- Purchase Orders
CREATE TABLE IF NOT EXISTS public.purchase_orders (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  manufacturer_id BIGINT REFERENCES manufacturers(id) ON DELETE SET NULL,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'draft',
  shipping_address JSONB,
  customer_order_number TEXT,
  lines JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- RFQs
CREATE TABLE IF NOT EXISTS public.rfqs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Saved Lists
CREATE TABLE IF NOT EXISTS public.saved_lists (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  name TEXT,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Ship-to Addresses
CREATE TABLE IF NOT EXISTS public.ship_to_addresses (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  label TEXT,
  address JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Contact Messages
CREATE TABLE IF NOT EXISTS public.contact_messages (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT,
  email TEXT,
  company TEXT,
  message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Password Reset Tokens
CREATE TABLE IF NOT EXISTS public.password_reset_tokens (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email TEXT NOT NULL,
  token TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Stripe Webhook Events (idempotency)
CREATE TABLE IF NOT EXISTS public.stripe_webhook_events (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  event_id TEXT NOT NULL UNIQUE,
  event_type TEXT NOT NULL,
  processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  payload JSONB
);

CREATE INDEX IF NOT EXISTS idx_stripe_events_id ON public.stripe_webhook_events (event_id);

-- Product Favorites
CREATE TABLE IF NOT EXISTS public.product_favorites (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, product_id)
);

-- Admin Users (for admin portal access)
CREATE TABLE IF NOT EXISTS public.admin_users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL UNIQUE,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- ROW LEVEL SECURITY (RLS)
-- =============================================================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ship_to_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_favorites ENABLE ROW LEVEL SECURITY;

-- Service role bypass for all tables
CREATE POLICY "Service role has full access to users" ON public.users FOR ALL USING (true);
CREATE POLICY "Service role has full access to orders" ON public.orders FOR ALL USING (true);
CREATE POLICY "Service role has full access to order_items" ON public.order_items FOR ALL USING (true);
CREATE POLICY "Service role has full access to carts" ON public.carts FOR ALL USING (true);
CREATE POLICY "Service role has full access to saved_lists" ON public.saved_lists FOR ALL USING (true);
CREATE POLICY "Service role has full access to ship_to_addresses" ON public.ship_to_addresses FOR ALL USING (true);
CREATE POLICY "Service role has full access to product_favorites" ON public.product_favorites FOR ALL USING (true);

-- Products are publicly readable
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Products are publicly readable" ON public.products FOR SELECT USING (true);
CREATE POLICY "Service role can manage products" ON public.products FOR ALL USING (true);

-- =============================================================================
-- DEMO USER (for testing)
-- =============================================================================

INSERT INTO public.users (company_name, email, password_hash, contact_name, is_approved, discount_tier)
VALUES ('Demo Company', 'demo@company.com', '$2a$10$N9qo8uLOickgx2ZMRZoMye/wCjHN2W5DLSN1YnCqQ3Vh6X/o6y.U6', 'Demo User', 1, 'standard')
ON CONFLICT (email) DO NOTHING;

SELECT 'Migrations applied successfully!' as status;
