const fs = require('fs');
const path = require('path');
const bcrypt = require('bcryptjs');

const DB_PATH = path.join(__dirname, 'database.json');

// Product data
const products = [
    // ============ HOSPECO PRODUCTS ============
    {
        id: 1,
        sku: 'GLV-GL-N105FX',
        name: 'ProWorks Nitrile Exam Gloves - Powder Free',
        brand: 'Hospeco',
        category: 'Disposable Gloves',
        subcategory: 'Nitrile',
        description: 'Premium quality nitrile exam gloves. Powder-free, latex-free formula provides excellent tactile sensitivity and durability. Textured fingertips for enhanced grip. Ideal for medical, food service, and industrial applications.',
        material: 'Nitrile',
        sizes: 'S,M,L,XL',
        color: 'Blue',
        pack_qty: 100,
        case_qty: 1000,
        price: 12.99,
        bulk_price: 9.99,
        image_url: 'https://via.placeholder.com/400x400/FFFFFF/0066CC?text=Blue+Nitrile',
        in_stock: 1,
        featured: 1
    },
    {
        id: 2,
        sku: 'GLV-GL-N105FB',
        name: 'ProWorks Nitrile Gloves - Black',
        brand: 'Hospeco',
        category: 'Disposable Gloves',
        subcategory: 'Nitrile',
        description: 'Professional-grade black nitrile gloves. Perfect for automotive, tattoo, and salon industries. Powder-free and latex-free with superior puncture resistance.',
        material: 'Nitrile',
        sizes: 'S,M,L,XL,2XL',
        color: 'Black',
        pack_qty: 100,
        case_qty: 1000,
        price: 14.99,
        bulk_price: 11.49,
        image_url: 'https://via.placeholder.com/400x400/FFFFFF/333333?text=Black+Nitrile+Gloves',
        in_stock: 1,
        featured: 1
    },
    {
        id: 3,
        sku: 'GLV-GL-L101F',
        name: 'ProWorks Latex Exam Gloves - Powder Free',
        brand: 'Hospeco',
        category: 'Disposable Gloves',
        subcategory: 'Latex',
        description: 'High-quality latex exam gloves with excellent elasticity and comfort. Powder-free formula reduces allergic reactions. Beaded cuff for easy donning.',
        material: 'Latex',
        sizes: 'S,M,L,XL',
        color: 'Natural',
        pack_qty: 100,
        case_qty: 1000,
        price: 10.99,
        bulk_price: 7.99,
        image_url: 'https://via.placeholder.com/400x400/FFFFFF/333333?text=Latex+Gloves',
        in_stock: 1,
        featured: 0
    },
    {
        id: 4,
        sku: 'GLV-GL-V104F',
        name: 'ProWorks Vinyl Gloves - Powder Free',
        brand: 'Hospeco',
        category: 'Disposable Gloves',
        subcategory: 'Vinyl',
        description: 'Economical vinyl gloves for light-duty applications. Latex-free and powder-free. Ideal for food handling, janitorial, and general purpose use.',
        material: 'Vinyl',
        sizes: 'S,M,L,XL',
        color: 'Clear',
        pack_qty: 100,
        case_qty: 1000,
        price: 7.99,
        bulk_price: 5.49,
        image_url: 'https://via.placeholder.com/400x400/FFFFFF/333333?text=Vinyl+Gloves',
        in_stock: 1,
        featured: 0
    },

    // ============ GLOBAL GLOVE PRODUCTS ============
    {
        id: 5,
        sku: 'GLV-705PFE',
        name: 'Panther-Guard Nitrile Gloves - Industrial Grade',
        brand: 'Global Glove',
        category: 'Disposable Gloves',
        subcategory: 'Nitrile',
        description: 'Industrial grade nitrile gloves with exceptional chemical resistance. 5 mil thickness provides durability for demanding applications. Textured for excellent wet and dry grip.',
        material: 'Nitrile',
        sizes: 'S,M,L,XL,2XL',
        color: 'Blue',
        pack_qty: 100,
        case_qty: 1000,
        price: 15.99,
        bulk_price: 12.49,
        image_url: 'https://via.placeholder.com/400x400/FFFFFF/0066CC?text=Panther-Guard+Blue',
        in_stock: 1,
        featured: 1
    },
    {
        id: 6,
        sku: 'GLV-705BPF',
        name: 'Panther-Guard Nitrile Gloves - Black Industrial',
        brand: 'Global Glove',
        category: 'Disposable Gloves',
        subcategory: 'Nitrile',
        description: 'Heavy-duty black nitrile gloves for industrial applications. 6 mil thickness offers superior protection. Chemical and puncture resistant.',
        material: 'Nitrile',
        sizes: 'S,M,L,XL,2XL',
        color: 'Black',
        pack_qty: 100,
        case_qty: 1000,
        price: 17.99,
        bulk_price: 13.99,
        image_url: 'https://via.placeholder.com/400x400/FFFFFF/000000?text=Panther-Guard+Black',
        in_stock: 1,
        featured: 1
    },
    {
        id: 7,
        sku: 'GLV-805PF',
        name: 'Panther-Guard Nitrile - 8 Mil Heavy Duty',
        brand: 'Global Glove',
        category: 'Disposable Gloves',
        subcategory: 'Nitrile',
        description: 'Extra thick 8 mil nitrile gloves for maximum protection. Raised diamond texture for superior grip. Extended cuff for added wrist protection.',
        material: 'Nitrile',
        sizes: 'M,L,XL,2XL',
        color: 'Orange',
        pack_qty: 50,
        case_qty: 500,
        price: 19.99,
        bulk_price: 15.99,
        image_url: 'https://via.placeholder.com/400x400/FFFFFF/FF6B00?text=8+Mil+Nitrile+HD',
        in_stock: 1,
        featured: 1
    },
    {
        id: 8,
        sku: 'GLV-500G',
        name: 'Gripster Foam Nitrile Coated Work Gloves',
        brand: 'Global Glove',
        category: 'Work Gloves',
        subcategory: 'Coated',
        description: 'Lightweight nylon shell with foam nitrile palm coating. Excellent dexterity and breathability. Perfect for assembly, packaging, and light industrial work.',
        material: 'Nylon/Nitrile',
        sizes: 'S,M,L,XL,2XL',
        color: 'Gray/Black',
        pack_qty: 12,
        case_qty: 144,
        price: 36.99,
        bulk_price: 28.99,
        image_url: 'https://via.placeholder.com/400x400/FFFFFF/333333?text=Gripster+Work+Gloves',
        in_stock: 1,
        featured: 1
    },
    {
        id: 9,
        sku: 'GLV-590MF',
        name: 'Samurai Glove - Cut Resistant A4',
        brand: 'Global Glove',
        category: 'Work Gloves',
        subcategory: 'Cut Resistant',
        description: 'ANSI A4 cut resistant gloves with micro-foam nitrile coating. Tuff-Grit technology for enhanced grip. Machine washable for extended use.',
        material: 'HPPE/Nitrile',
        sizes: 'S,M,L,XL,2XL',
        color: 'Green/Black',
        pack_qty: 12,
        case_qty: 72,
        price: 89.99,
        bulk_price: 69.99,
        image_url: 'https://via.placeholder.com/400x400/FFFFFF/00AA00?text=Samurai+Cut+A4',
        in_stock: 1,
        featured: 0
    },
    {
        id: 10,
        sku: 'GLV-CR509',
        name: 'CIA Global Impact Resistant Gloves',
        brand: 'Global Glove',
        category: 'Work Gloves',
        subcategory: 'Impact Resistant',
        description: 'Cut, impact, and abrasion resistant work gloves. TPR impact protection on back of hand and fingers. ANSI A5 cut level with nitrile palm.',
        material: 'HPPE/TPR',
        sizes: 'M,L,XL,2XL',
        color: 'Black/Orange',
        pack_qty: 12,
        case_qty: 48,
        price: 149.99,
        bulk_price: 119.99,
        image_url: 'https://via.placeholder.com/400x400/FFFFFF/FF6B00?text=Impact+Resistant',
        in_stock: 1,
        featured: 1
    },

    // ============ SAFEKO PRODUCTS ============
    {
        id: 11,
        sku: 'GLV-SAF-N100',
        name: 'Safeko Nitrile Exam Gloves - Premium',
        brand: 'Safeko',
        category: 'Disposable Gloves',
        subcategory: 'Nitrile',
        description: 'Premium nitrile exam gloves with superior fit and feel. 4 mil thickness balances protection and sensitivity. Micro-textured surface for precise handling.',
        material: 'Nitrile',
        sizes: 'XS,S,M,L,XL',
        color: 'Blue',
        pack_qty: 100,
        case_qty: 1000,
        price: 13.49,
        bulk_price: 10.49,
        image_url: 'https://via.placeholder.com/400x400/FFFFFF/0066CC?text=Safeko+Nitrile',
        in_stock: 1,
        featured: 0
    },
    {
        id: 12,
        sku: 'GLV-SAF-N200',
        name: 'Safeko Nitrile Gloves - Food Service',
        brand: 'Safeko',
        category: 'Disposable Gloves',
        subcategory: 'Nitrile',
        description: 'FDA compliant nitrile gloves for food handling. Blue color for easy detection. Powder-free and ambidextrous design.',
        material: 'Nitrile',
        sizes: 'S,M,L,XL',
        color: 'Blue',
        pack_qty: 100,
        case_qty: 1000,
        price: 11.99,
        bulk_price: 8.99,
        image_url: 'https://via.placeholder.com/400x400/FFFFFF/0066CC?text=Food+Service',
        in_stock: 1,
        featured: 0
    },
    {
        id: 13,
        sku: 'GLV-SAF-V100',
        name: 'Safeko Vinyl Gloves - Economy',
        brand: 'Safeko',
        category: 'Disposable Gloves',
        subcategory: 'Vinyl',
        description: 'Cost-effective vinyl gloves for general purpose use. Latex and powder free. Great for short-duration tasks.',
        material: 'Vinyl',
        sizes: 'S,M,L,XL',
        color: 'Clear',
        pack_qty: 100,
        case_qty: 1000,
        price: 6.99,
        bulk_price: 4.99,
        image_url: 'https://via.placeholder.com/400x400/FFFFFF/333333?text=Safeko+Vinyl',
        in_stock: 1,
        featured: 0
    },

    // ============ OTHER BRANDS ============
    {
        id: 14,
        sku: 'GLV-AMS-N300',
        name: 'Ambitex Nitrile Select - Blue',
        brand: 'Ambitex',
        category: 'Disposable Gloves',
        subcategory: 'Nitrile',
        description: 'High-quality nitrile gloves at an economical price point. Powder-free with textured fingertips. Suitable for medical and industrial use.',
        material: 'Nitrile',
        sizes: 'S,M,L,XL',
        color: 'Blue',
        pack_qty: 100,
        case_qty: 1000,
        price: 11.49,
        bulk_price: 8.49,
        image_url: 'https://via.placeholder.com/400x400/FFFFFF/0066CC?text=Ambitex+Nitrile',
        in_stock: 1,
        featured: 0
    },
    {
        id: 15,
        sku: 'GLV-PIP-34874',
        name: 'PIP MaxiFlex Ultimate Gloves',
        brand: 'PIP',
        category: 'Work Gloves',
        subcategory: 'Coated',
        description: 'Industry-leading coated work gloves with micro-foam nitrile. 360-degree breathability with patented coating technology. Silicone-free.',
        material: 'Nylon/Nitrile',
        sizes: 'XS,S,M,L,XL,2XL,3XL',
        color: 'Gray/Black',
        pack_qty: 12,
        case_qty: 144,
        price: 48.99,
        bulk_price: 38.99,
        image_url: 'https://via.placeholder.com/400x400/FFFFFF/333333?text=MaxiFlex+Ultimate',
        in_stock: 1,
        featured: 1
    },
    {
        id: 16,
        sku: 'GLV-PIP-34876',
        name: 'PIP MaxiFlex Cut A3 Gloves',
        brand: 'PIP',
        category: 'Work Gloves',
        subcategory: 'Cut Resistant',
        description: 'ANSI A3 cut resistant gloves with micro-foam nitrile coating. Engineered yarn for flexibility and dexterity. Machine washable.',
        material: 'Engineered Yarn/Nitrile',
        sizes: 'XS,S,M,L,XL,2XL',
        color: 'Green/Black',
        pack_qty: 12,
        case_qty: 72,
        price: 64.99,
        bulk_price: 51.99,
        image_url: 'https://via.placeholder.com/400x400/FFFFFF/00AA00?text=MaxiFlex+Cut+A3',
        in_stock: 1,
        featured: 0
    },
    {
        id: 17,
        sku: 'GLV-MCR-9672',
        name: 'MCR Safety UltraTech Foam Nitrile',
        brand: 'MCR Safety',
        category: 'Work Gloves',
        subcategory: 'Coated',
        description: 'Premium foam nitrile coated work gloves. 15-gauge nylon shell for excellent dexterity. Foam nitrile provides breathability and grip.',
        material: 'Nylon/Nitrile',
        sizes: 'S,M,L,XL,2XL',
        color: 'Gray/Blue',
        pack_qty: 12,
        case_qty: 144,
        price: 42.99,
        bulk_price: 33.99,
        image_url: 'https://via.placeholder.com/400x400/FFFFFF/0066CC?text=UltraTech+Foam',
        in_stock: 1,
        featured: 0
    },
    {
        id: 18,
        sku: 'GLV-ANS-11800',
        name: 'Ansell HyFlex 11-800 Foam Nitrile',
        brand: 'Ansell',
        category: 'Work Gloves',
        subcategory: 'Coated',
        description: 'Ultra-lightweight foam nitrile coated gloves. 18-gauge nylon liner for maximum dexterity. Excellent for precision assembly.',
        material: 'Nylon/Nitrile',
        sizes: 'S,M,L,XL',
        color: 'Gray',
        pack_qty: 12,
        case_qty: 144,
        price: 54.99,
        bulk_price: 43.99,
        image_url: 'https://via.placeholder.com/400x400/FFFFFF/666666?text=HyFlex+11-800',
        in_stock: 1,
        featured: 0
    },
    {
        id: 19,
        sku: 'GLV-SHW-370',
        name: 'SHOWA Atlas 370 Nitrile Gloves',
        brand: 'SHOWA',
        category: 'Work Gloves',
        subcategory: 'Coated',
        description: 'Original assembly grip gloves. Flat nitrile palm coating offers excellent dry grip. Seamless knit liner for comfort.',
        material: 'Nylon/Nitrile',
        sizes: 'XS,S,M,L,XL,2XL',
        color: 'Black',
        pack_qty: 12,
        case_qty: 144,
        price: 39.99,
        bulk_price: 31.99,
        image_url: 'https://via.placeholder.com/400x400/FFFFFF/000000?text=SHOWA+Atlas+370',
        in_stock: 1,
        featured: 0
    },
    {
        id: 20,
        sku: 'GLV-WSL-111',
        name: 'Wells Lamont Leather Work Gloves',
        brand: 'Wells Lamont',
        category: 'Work Gloves',
        subcategory: 'Leather',
        description: 'Premium grain leather work gloves with keystone thumb. Shirred elastic wrist for secure fit. Ideal for general construction and yard work.',
        material: 'Cowhide Leather',
        sizes: 'S,M,L,XL',
        color: 'Tan',
        pack_qty: 12,
        case_qty: 72,
        price: 119.99,
        bulk_price: 94.99,
        image_url: 'https://via.placeholder.com/400x400/FFFFFF/D2B48C?text=Leather+Work+Gloves',
        in_stock: 1,
        featured: 0
    }
];

// Create demo user
const hashedPassword = bcrypt.hashSync('demo123', 10);
const demoUser = {
    id: 1,
    company_name: 'Demo Company Inc',
    email: 'demo@company.com',
    password: hashedPassword,
    contact_name: 'John Demo',
    phone: '555-123-4567',
    address: '123 Demo Street',
    city: 'Chicago',
    state: 'IL',
    zip: '60601',
    is_approved: 1,
    discount_tier: 'silver',
    created_at: new Date().toISOString()
};

// Create database
const db = {
    users: [demoUser],
    products: products,
    orders: [],
    carts: {}
};

// Save database
fs.writeFileSync(DB_PATH, JSON.stringify(db, null, 2));

console.log(`\n✅ Database seeded successfully!`);
console.log(`   - ${products.length} products added`);
console.log(`   - Demo user created: demo@company.com / demo123`);
console.log(`\n🚀 Run 'npm start' to launch the server\n`);
