import type { LucideIcon } from "lucide-react";
import {
  LayoutGrid,
  Stethoscope,
  UtensilsCrossed,
  Brush,
  Factory,
  Car,
  Smile,
  PawPrint,
  FlaskConical,
  Pill,
  Sparkles,
  PenTool,
  ChefHat,
  GraduationCap,
  ShoppingBag,
  Cpu,
  HardHat,
  Truck,
  Scissors,
  Beaker,
  Shield,
  Hand,
  Snowflake,
  Sprout,
  Fuel,
  TreeDeciduous,
  Flame,
  ShieldAlert,
  Package,
} from "lucide-react";

/** Lucide icon per `HEADER_INDUSTRY_NAV_ITEMS[].href` (exact string match). */
const INDUSTRY_NAV_ICON_BY_HREF: Record<string, LucideIcon> = {
  "/industries": LayoutGrid,
  "/industries/healthcare": Stethoscope,
  "/industries/hospitality": UtensilsCrossed,
  "/industries/janitorial": Brush,
  "/industries/industrial": Factory,
  "/store?industries=automotive": Car,
  "/store?industries=dental": Smile,
  "/store?industries=veterinary": PawPrint,
  "/store?industries=laboratories": FlaskConical,
  "/store?industries=pharmaceuticals": Pill,
  "/store?industries=beauty_personal_care": Sparkles,
  "/store?industries=tattoo_body_art": PenTool,
  "/store?industries=food_processing": ChefHat,
  "/store?industries=education": GraduationCap,
  "/store?industries=retail_grocery": ShoppingBag,
  "/store?industries=electronics_assembly": Cpu,
  "/store?industries=construction": HardHat,
  "/store?industries=warehousing_logistics": Truck,
  "/store?industries=metal_fabrication": Scissors,
  "/store?industries=chemical_processing": Beaker,
  "/store?category=chemical-resistant&industries=chemical_processing": Shield,
  "/store?category=work-gloves&industries=industrial": Hand,
  "/store?industries=cold_chain_outdoor": Snowflake,
  "/store?industries=agriculture": Sprout,
  "/store?industries=oil_gas_energy": Fuel,
  "/store?industries=landscaping_grounds": TreeDeciduous,
  "/store?industries=emergency_services": Flame,
  "/store?industries=security_public_safety": ShieldAlert,
  "/store?industries=janitorial%2Csanitation": Package,
};

export function industryNavIconForHref(href: string): LucideIcon {
  return INDUSTRY_NAV_ICON_BY_HREF[href] ?? LayoutGrid;
}
