-- Run this in Supabase Dashboard → SQL Editor if you get:
--   "Could not find the table 'public.users' in the schema cache"
-- Then reload the schema (Dashboard → Settings → API → "Reload schema cache" if available)
-- or wait a few seconds for PostgREST to pick up the new table.
-- Note: company_id is UUID to match public.companies(id) if that table uses UUID.

-- Create public.users (company_id matches existing companies.id type: UUID)
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  company_name TEXT,
  company_id UUID REFERENCES public.companies(id) ON DELETE SET NULL,
  contact_name TEXT,
  phone TEXT,
  address TEXT,
  city TEXT,
  state TEXT,
  zip TEXT,
  is_approved SMALLINT NOT NULL DEFAULT 0,
  discount_tier TEXT NOT NULL DEFAULT 'standard',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  budget_amount NUMERIC(12,2),
  budget_period TEXT DEFAULT 'monthly',
  rep_name TEXT,
  rep_email TEXT,
  rep_phone TEXT,
  cases_or_pallets TEXT,
  allow_free_upgrades BOOLEAN DEFAULT false,
  payment_terms TEXT DEFAULT 'credit_card'
);

CREATE INDEX IF NOT EXISTS idx_users_email ON public.users (LOWER(email));

-- Create public.app_admins
CREATE TABLE IF NOT EXISTS public.app_admins (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  email TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id),
  UNIQUE(email)
);

CREATE INDEX IF NOT EXISTS idx_app_admins_user_id ON public.app_admins (user_id);
CREATE INDEX IF NOT EXISTS idx_app_admins_email ON public.app_admins (LOWER(email));
