/**
 * Canonical field names for AI CSV mapping.
 * These align with what extractContentFromRaw and attribute extractors expect.
 */

export const CANONICAL_CSV_FIELDS = [
  "supplier_sku",
  "manufacturer_sku",
  "product_name",
  "brand",
  "description",
  "material",
  "thickness_mil",
  "color",
  "size",
  "powder_free",
  "grade",
  "gloves_per_box",
  "boxes_per_case",
  "case_price",
  "box_price",
  "image_url",
  "name",
  "title",
  "sku",
  "item",
  "item_number",
  "product_id",
  "id",
  "cost",
  "price",
  "unit_cost",
  "list_price",
  "supplier_cost",
  "short_description",
  "long_description",
  "upc",
  "gtin",
  "case_qty",
  "box_qty",
  "qty_per_case",
  "pack_qty",
  "lead_time_days",
  "stock_status",
  "uom",
  "unit_of_measure",
  "unit",
  "sell_uom",
  "um",
  "pack_size",
  "case_pack",
  "category_guess",
  "product_category",
  "category",
  "family",
  "variant_value",
] as const;

export type CanonicalFieldName = (typeof CANONICAL_CSV_FIELDS)[number];

/** Fields that normalization-utils firstStr/content expect (primary aliases). */
export const PRIMARY_CONTENT_KEYS = [
  "name",
  "title",
  "product_name",
  "sku",
  "item",
  "item_number",
  "product_id",
  "id",
  "supplier_sku",
  "cost",
  "price",
  "unit_cost",
  "list_price",
  "supplier_cost",
  "case_price",
  "image_url",
  "brand",
  "description",
  "case_qty",
  "box_qty",
  "gloves_per_box",
  "uom",
  "unit_of_measure",
  "pack_size",
  "category_guess",
  "variant_value",
] as const;
