-- Idempotent: companies, company_members (assumed to exist; ensure structure)
-- No raw credit card data; Stripe IDs only if needed later.

-- Companies: id, name, default_gross_margin_percent (editable in admin)
CREATE TABLE IF NOT EXISTS companies (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add default_gross_margin_percent if missing (e.g. existing companies table)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'companies' AND column_name = 'default_gross_margin_percent'
  ) THEN
    ALTER TABLE companies ADD COLUMN default_gross_margin_percent NUMERIC(5,2) DEFAULT 30 CHECK (default_gross_margin_percent >= 0 AND default_gross_margin_percent < 100);
  END IF;
END $$;

-- Company members (user-company link; assumed to exist)
CREATE TABLE IF NOT EXISTS company_members (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL,
  role TEXT DEFAULT 'member',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(company_id, user_id)
);
