-- Net terms / invoice workflow: company commercial fields + application queue.
-- Existing rows default to legacy (checkout continues to use user.is_approved for invoice until approved via workflow).

ALTER TABLE public.companies
  ADD COLUMN IF NOT EXISTS net_terms_status TEXT NOT NULL DEFAULT 'legacy';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'companies_net_terms_status_check'
  ) THEN
    ALTER TABLE public.companies
      ADD CONSTRAINT companies_net_terms_status_check
      CHECK (net_terms_status IN ('legacy', 'pending', 'approved', 'denied', 'on_hold', 'revoked'));
  END IF;
END $$;

ALTER TABLE public.companies
  ADD COLUMN IF NOT EXISTS credit_limit NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS outstanding_balance NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS invoice_terms_code TEXT,
  ADD COLUMN IF NOT EXISTS invoice_terms_custom TEXT,
  ADD COLUMN IF NOT EXISTS invoice_orders_allowed BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS net_terms_internal_notes TEXT,
  ADD COLUMN IF NOT EXISTS net_terms_reviewed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS net_terms_reviewed_by_user_id BIGINT REFERENCES public.users(id);

CREATE TABLE IF NOT EXISTS public.net_terms_applications (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  applicant_user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending',
  business_name TEXT NOT NULL,
  contact_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  billing_address_line1 TEXT,
  billing_city TEXT,
  billing_state TEXT,
  billing_zip TEXT,
  ein_tax_id TEXT,
  years_in_business TEXT,
  requested_credit_limit NUMERIC(14,2),
  monthly_estimated_spend NUMERIC(14,2),
  trade_references TEXT,
  tax_exempt BOOLEAN NOT NULL DEFAULT false,
  tax_certificate_note TEXT,
  reviewed_by_user_id BIGINT REFERENCES public.users(id),
  reviewed_at TIMESTAMPTZ,
  decision_notes TEXT,
  approved_credit_limit NUMERIC(14,2),
  approved_invoice_terms_code TEXT,
  approved_invoice_orders_allowed BOOLEAN,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT net_terms_applications_status_check CHECK (status IN ('pending', 'approved', 'denied', 'on_hold', 'revoked'))
);

CREATE INDEX IF NOT EXISTS idx_net_terms_applications_company_id ON public.net_terms_applications(company_id);
CREATE INDEX IF NOT EXISTS idx_net_terms_applications_status ON public.net_terms_applications(status);
CREATE INDEX IF NOT EXISTS idx_net_terms_applications_created ON public.net_terms_applications(created_at DESC);

COMMENT ON TABLE public.net_terms_applications IS 'B2B net terms / invoice checkout applications; company may stay legacy until approved.';
COMMENT ON COLUMN public.companies.outstanding_balance IS 'AR-oriented running balance; not auto-posted from orders in this schema.';
COMMENT ON COLUMN public.companies.net_terms_status IS 'legacy = invoice gated by user.is_approved only; pending = application under review; approved/denied/on_hold/revoked = commercial workflow.';
