-- =============================================================================
-- GloveCubs: public.users, public.app_admins, public.products slug/display cols.
-- Enables Express app to use Supabase as single source of truth (no database.json).
-- If you see "Could not find the table 'public.users' in the schema cache", run
-- this migration (e.g. Supabase SQL Editor or: supabase db push).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1) public.products: add slug and display columns if missing
-- -----------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'slug') THEN
    ALTER TABLE products ADD COLUMN slug TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'price') THEN
    ALTER TABLE products ADD COLUMN price NUMERIC(12,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'bulk_price') THEN
    ALTER TABLE products ADD COLUMN bulk_price NUMERIC(12,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'in_stock') THEN
    ALTER TABLE products ADD COLUMN in_stock SMALLINT DEFAULT 1;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'featured') THEN
    ALTER TABLE products ADD COLUMN featured SMALLINT DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'use_case') THEN
    ALTER TABLE products ADD COLUMN use_case TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'certifications') THEN
    ALTER TABLE products ADD COLUMN certifications TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'texture') THEN
    ALTER TABLE products ADD COLUMN texture TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'cuff_style') THEN
    ALTER TABLE products ADD COLUMN cuff_style TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'sterility') THEN
    ALTER TABLE products ADD COLUMN sterility TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'video_url') THEN
    ALTER TABLE products ADD COLUMN video_url TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'industry_tags') THEN
    ALTER TABLE products ADD COLUMN industry_tags JSONB DEFAULT '[]'::jsonb;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS products_slug_unique ON products (slug) WHERE slug IS NOT NULL;

-- -----------------------------------------------------------------------------
-- 2) public.users (replaces database.json users)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  company_name TEXT,
  company_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
  contact_name TEXT,
  phone TEXT,
  address TEXT,
  city TEXT,
  state TEXT,
  zip TEXT,
  is_approved SMALLINT NOT NULL DEFAULT 0,
  discount_tier TEXT NOT NULL DEFAULT 'standard',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  budget_amount NUMERIC(12,2),
  budget_period TEXT DEFAULT 'monthly',
  rep_name TEXT,
  rep_email TEXT,
  rep_phone TEXT,
  cases_or_pallets TEXT,
  allow_free_upgrades BOOLEAN DEFAULT false,
  payment_terms TEXT DEFAULT 'credit_card'
);

CREATE INDEX IF NOT EXISTS idx_users_email ON public.users (LOWER(email));

-- -----------------------------------------------------------------------------
-- 3) public.app_admins (user_id or email for admin check)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.app_admins (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  email TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id),
  UNIQUE(email)
);

CREATE INDEX IF NOT EXISTS idx_app_admins_user_id ON public.app_admins (user_id);
CREATE INDEX IF NOT EXISTS idx_app_admins_email ON public.app_admins (LOWER(email));

COMMENT ON TABLE public.users IS 'GloveCubs B2B users; migrated from database.json.';
COMMENT ON TABLE public.app_admins IS 'GloveCubs app admins; user_id or email.';

-- Seed demo user (demo@company.com / demo123) if not present
INSERT INTO public.users (email, password_hash, company_name, contact_name, phone, address, city, state, zip, is_approved, discount_tier)
SELECT 'demo@company.com', '$2a$10$7nnjp9KcyS8aFsRkE1dvEumROrZEldTROMteztG3UZXZQqw8lWFFe', 'Demo Company Inc', 'John Demo', '555-123-4567', '123 Demo Street', 'Chicago', 'IL', '60601', 1, 'silver'
WHERE NOT EXISTS (SELECT 1 FROM public.users WHERE LOWER(email) = 'demo@company.com');
