-- Idempotent: customer_manufacturer_pricing (per-company, per-manufacturer margin override)
-- Constraint: unique (company_id, manufacturer_id); no ADD CONSTRAINT IF NOT EXISTS per spec.
CREATE TABLE IF NOT EXISTS customer_manufacturer_pricing (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  manufacturer_id BIGINT NOT NULL REFERENCES manufacturers(id) ON DELETE CASCADE,
  margin_percent NUMERIC(5,2) NOT NULL CHECK (margin_percent >= 0 AND margin_percent < 100),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(company_id, manufacturer_id)
);

CREATE INDEX IF NOT EXISTS idx_customer_manufacturer_pricing_company
  ON customer_manufacturer_pricing(company_id);
