-- Net 30 / AR for gc_commerce.orders (UUID): invoice columns, payment ledger, RPCs.
-- Company balance + credit_limit remain on public.companies (legacy_company_id bridge).

ALTER TABLE gc_commerce.orders
  ADD COLUMN IF NOT EXISTS invoice_status TEXT,
  ADD COLUMN IF NOT EXISTS invoice_amount_due NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS invoice_amount_paid NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS invoice_due_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS invoice_terms_code_applied TEXT,
  ADD COLUMN IF NOT EXISTS invoice_ar_opened_at TIMESTAMPTZ;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'gc_orders_invoice_status_check'
  ) THEN
    ALTER TABLE gc_commerce.orders
      ADD CONSTRAINT gc_orders_invoice_status_check
      CHECK (
        invoice_status IS NULL
        OR invoice_status IN ('unpaid', 'partially_paid', 'paid')
      );
  END IF;
END $$;

COMMENT ON COLUMN gc_commerce.orders.invoice_ar_opened_at IS
  'When set, net30 AR was posted (public.companies.outstanding_balance + open invoice). Idempotent.';

CREATE TABLE IF NOT EXISTS gc_commerce.ar_invoice_payments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  order_id UUID NOT NULL REFERENCES gc_commerce.orders (id) ON DELETE CASCADE,
  legacy_company_id BIGINT REFERENCES public.companies (id) ON DELETE SET NULL,
  amount NUMERIC(14,2) NOT NULL,
  note TEXT,
  recorded_by_legacy_user_id BIGINT REFERENCES public.users (id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT gc_ar_invoice_payments_amount_positive CHECK (amount > 0)
);

CREATE INDEX IF NOT EXISTS idx_gc_ar_invoice_payments_order_id
  ON gc_commerce.ar_invoice_payments (order_id);
CREATE INDEX IF NOT EXISTS idx_gc_ar_invoice_payments_legacy_company_id
  ON gc_commerce.ar_invoice_payments (legacy_company_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON gc_commerce.ar_invoice_payments TO postgres, service_role;

-- Open AR on a gc order: row-lock order + legacy company, credit check, then invoice fields + balance.
CREATE OR REPLACE FUNCTION public.glovecubs_apply_net30_order_ar_gc(
  p_order_id UUID,
  p_legacy_company_id BIGINT,
  p_amount NUMERIC,
  p_terms_code TEXT,
  p_due_at TIMESTAMPTZ
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, gc_commerce
AS $$
DECLARE
  v_opened TIMESTAMPTZ;
  v_credit_limit NUMERIC;
  v_out NUMERIC;
  v_projected NUMERIC;
  v_avail NUMERIC;
BEGIN
  IF p_order_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'invalid_order_id');
  END IF;

  IF p_amount IS NULL OR p_amount < 0 THEN
    RETURN jsonb_build_object('ok', false, 'error', 'invalid_amount');
  END IF;

  IF p_legacy_company_id IS NULL AND p_amount > 0 THEN
    RETURN jsonb_build_object('ok', false, 'error', 'legacy_company_required');
  END IF;

  SELECT o.invoice_ar_opened_at INTO v_opened
  FROM gc_commerce.orders o
  WHERE o.id = p_order_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'order_not_found');
  END IF;

  IF v_opened IS NOT NULL THEN
    RETURN jsonb_build_object('ok', true, 'skipped', true);
  END IF;

  IF p_legacy_company_id IS NOT NULL AND p_amount > 0 THEN
    SELECT c.credit_limit, COALESCE(c.outstanding_balance, 0)
    INTO v_credit_limit, v_out
    FROM public.companies c
    WHERE c.id = p_legacy_company_id
    FOR UPDATE;

    IF FOUND AND v_credit_limit IS NOT NULL THEN
      v_projected := round(v_out + p_amount, 2);
      v_avail := round(v_credit_limit - v_out, 2);
      IF v_projected > v_credit_limit THEN
        RETURN jsonb_build_object(
          'ok', false,
          'error', 'CREDIT_LIMIT_EXCEEDED',
          'credit_limit', v_credit_limit,
          'outstanding_balance', v_out,
          'order_total', p_amount,
          'projected_outstanding', v_projected,
          'available_credit', GREATEST(0, v_avail)
        );
      END IF;
    END IF;
  END IF;

  UPDATE gc_commerce.orders SET
    invoice_status = 'unpaid',
    invoice_amount_due = p_amount,
    invoice_amount_paid = 0,
    invoice_due_at = p_due_at,
    invoice_terms_code_applied = NULLIF(trim(COALESCE(p_terms_code, '')), ''),
    invoice_ar_opened_at = NOW(),
    updated_at = NOW()
  WHERE id = p_order_id;

  IF p_legacy_company_id IS NOT NULL AND p_amount > 0 THEN
    UPDATE public.companies SET
      outstanding_balance = round(COALESCE(outstanding_balance, 0) + p_amount, 2),
      updated_at = NOW()
    WHERE id = p_legacy_company_id;
  END IF;

  RETURN jsonb_build_object('ok', true, 'skipped', false);
END;
$$;

CREATE OR REPLACE FUNCTION public.glovecubs_record_invoice_payment_gc(
  p_order_id UUID,
  p_legacy_company_id BIGINT,
  p_amount NUMERIC,
  p_note TEXT,
  p_admin_legacy_user_id BIGINT
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, gc_commerce
AS $$
DECLARE
  v_due NUMERIC;
  v_paid NUMERIC;
  v_new_paid NUMERIC;
  v_remaining NUMERIC;
  v_apply NUMERIC;
  v_status TEXT;
BEGIN
  IF p_order_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'invalid_order_id');
  END IF;

  IF p_legacy_company_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'legacy_company_required');
  END IF;

  IF p_amount IS NULL OR p_amount <= 0 THEN
    RETURN jsonb_build_object('ok', false, 'error', 'invalid_amount');
  END IF;

  SELECT o.invoice_amount_due, COALESCE(o.invoice_amount_paid, 0)
  INTO v_due, v_paid
  FROM gc_commerce.orders o
  WHERE o.id = p_order_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'order_not_found');
  END IF;

  IF v_due IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_invoice_order');
  END IF;

  v_remaining := round(v_due - v_paid, 2);
  IF v_remaining <= 0 THEN
    RETURN jsonb_build_object('ok', false, 'error', 'already_paid');
  END IF;

  v_apply := round(LEAST(p_amount, v_remaining), 2);
  IF v_apply <= 0 THEN
    RETURN jsonb_build_object('ok', false, 'error', 'nothing_to_pay');
  END IF;

  INSERT INTO gc_commerce.ar_invoice_payments (
    order_id,
    legacy_company_id,
    amount,
    note,
    recorded_by_legacy_user_id
  ) VALUES (
    p_order_id,
    p_legacy_company_id,
    v_apply,
    NULLIF(trim(COALESCE(p_note, '')), ''),
    p_admin_legacy_user_id
  );

  v_new_paid := round(v_paid + v_apply, 2);

  IF v_new_paid + 0.005 >= v_due THEN
    v_status := 'paid';
  ELSIF v_new_paid > 0 THEN
    v_status := 'partially_paid';
  ELSE
    v_status := 'unpaid';
  END IF;

  UPDATE gc_commerce.orders SET
    invoice_amount_paid = v_new_paid,
    invoice_status = v_status,
    updated_at = NOW()
  WHERE id = p_order_id;

  IF p_legacy_company_id IS NOT NULL THEN
    UPDATE public.companies SET
      outstanding_balance = GREATEST(0, round(COALESCE(outstanding_balance, 0) - v_apply, 2)),
      updated_at = NOW()
    WHERE id = p_legacy_company_id;
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'amount_applied', v_apply,
    'invoice_status', v_status,
    'invoice_amount_paid', v_new_paid,
    'invoice_amount_due', v_due
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.glovecubs_apply_net30_order_ar_gc(UUID, BIGINT, NUMERIC, TEXT, TIMESTAMPTZ) TO service_role;
GRANT EXECUTE ON FUNCTION public.glovecubs_record_invoice_payment_gc(UUID, BIGINT, NUMERIC, TEXT, BIGINT) TO service_role;
