-- AI layer: conversations, invoice uploads, lines, recommendations (summaries only; no raw invoice text by default)

-- Conversations (glove-finder and similar)
CREATE TABLE IF NOT EXISTS ai_conversations (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NULL,
  ip_hash TEXT NULL,
  kind TEXT NOT NULL DEFAULT 'glove_finder',
  request_summary TEXT NULL,
  response_summary TEXT NULL,
  meta JSONB NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_conversations_user_id ON ai_conversations(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_conversations_created_at ON ai_conversations(created_at);

-- Invoice uploads (store metadata + extraction summary only)
CREATE TABLE IF NOT EXISTS invoice_uploads (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NULL,
  ip_hash TEXT NULL,
  file_name TEXT NULL,
  vendor_name TEXT NULL,
  invoice_number TEXT NULL,
  total_amount NUMERIC(12,2) NULL,
  line_count INT NULL,
  extract_summary TEXT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_invoice_uploads_user_id ON invoice_uploads(user_id);
CREATE INDEX IF NOT EXISTS idx_invoice_uploads_created_at ON invoice_uploads(created_at);

-- Invoice lines (extracted line items, no raw text)
CREATE TABLE IF NOT EXISTS invoice_lines (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  upload_id BIGINT NOT NULL REFERENCES invoice_uploads(id) ON DELETE CASCADE,
  line_index INT NOT NULL DEFAULT 0,
  description TEXT NULL,
  quantity NUMERIC(12,2) NOT NULL DEFAULT 0,
  unit_price NUMERIC(12,2) NULL,
  total NUMERIC(12,2) NULL,
  sku_or_code TEXT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_invoice_lines_upload_id ON invoice_lines(upload_id);

-- Recommendations (per upload or per conversation)
CREATE TABLE IF NOT EXISTS recommendations (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  upload_id BIGINT NULL REFERENCES invoice_uploads(id) ON DELETE SET NULL,
  conversation_id BIGINT NULL REFERENCES ai_conversations(id) ON DELETE SET NULL,
  line_index INT NULL,
  current_product TEXT NULL,
  recommended_sku TEXT NULL,
  recommended_name TEXT NOT NULL,
  brand TEXT NULL,
  estimated_savings NUMERIC(12,2) NULL,
  reason TEXT NULL,
  meta JSONB NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_recommendations_upload_id ON recommendations(upload_id);
CREATE INDEX IF NOT EXISTS idx_recommendations_conversation_id ON recommendations(conversation_id);
