-- Versioned shipping policy (threshold, flat rate, min order). Active = latest row with effective_at <= now().
-- Checkout reads DB when configured; orders store shipping_policy_version_id for experiment analysis.

CREATE TABLE IF NOT EXISTS public.shipping_policy_versions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  free_shipping_threshold NUMERIC(14, 2) NOT NULL,
  flat_shipping_rate NUMERIC(14, 2) NOT NULL,
  min_order_amount NUMERIC(14, 2) NOT NULL,
  effective_at TIMESTAMPTZ NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_shipping_policy_versions_effective_at
  ON public.shipping_policy_versions (effective_at DESC, id DESC);

COMMENT ON TABLE public.shipping_policy_versions IS 'Commerce shipping/min-order rules; active version is max(effective_at) where effective_at <= transaction time.';
COMMENT ON COLUMN public.shipping_policy_versions.effective_at IS 'Instant this version becomes (or became) the rule for new checkouts.';

-- Baseline row when table is empty (align with env in production if you use different defaults).
INSERT INTO public.shipping_policy_versions (free_shipping_threshold, flat_shipping_rate, min_order_amount, effective_at, notes)
SELECT 500, 25, 200, '2000-01-01T00:00:00Z', 'Seed baseline; add versions with effective_at = now() to change live policy.'
WHERE NOT EXISTS (SELECT 1 FROM public.shipping_policy_versions LIMIT 1);

ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS shipping_policy_version_id BIGINT REFERENCES public.shipping_policy_versions (id);

COMMENT ON COLUMN public.orders.shipping_policy_version_id IS 'FK to shipping_policy_versions in effect when the order was placed.';
