-- =============================================================================
-- Blank-project prerequisite: create public.sales_prospects before
-- 20260506120000 references it from procurement_opportunities.
--
-- Creation was deferred to 20260704120000_growth_pipeline_prospects.sql, which
-- sorts AFTER the procurement spine FK — breaking empty-project pushes.
-- Shape matches 20260704120000 so CREATE TABLE IF NOT EXISTS there is a no-op.
-- 20260707120000 may later convert created_by_admin_user_id bigint → uuid.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.sales_prospects (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_name TEXT NOT NULL,
  contact_name TEXT,
  email TEXT,
  phone TEXT,
  source TEXT,
  status TEXT NOT NULL DEFAULT 'new',
  notes TEXT,
  converted_company_id BIGINT REFERENCES public.companies (id) ON DELETE SET NULL,
  created_by_admin_user_id BIGINT REFERENCES public.users (id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_contacted_at TIMESTAMPTZ,
  CONSTRAINT sales_prospects_status_check CHECK (
    status IN ('new', 'contacted', 'quoted', 'negotiating', 'won', 'lost', 'nurture')
  )
);

CREATE INDEX IF NOT EXISTS idx_sales_prospects_status ON public.sales_prospects (status);
CREATE INDEX IF NOT EXISTS idx_sales_prospects_created ON public.sales_prospects (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sales_prospects_email_lower ON public.sales_prospects (LOWER(email));

COMMENT ON TABLE public.sales_prospects IS 'Early-stage B2B leads; keep small-set workflows outside full CRM.';

-- Deny-by-default for PostgREST roles. Admin growth APIs use the service role (bypasses RLS).
ALTER TABLE public.sales_prospects ENABLE ROW LEVEL SECURITY;
