-- Supplier cost → derived list/bulk pricing: audit runs, line-level explainability, optional named rule sets.
-- Writes to public.products (cost, price, bulk_price, pricing_derivation) — same fields used by cart/quote/commerce-pricing.

ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS pricing_derivation JSONB;

COMMENT ON COLUMN public.products.pricing_derivation IS 'Last supplier-cost pricing engine output: source cost, rule snapshot, formula steps, reference tier prices.';

-- Named margin / MAP rule presets (optional; UI may also send inline rules per run).
CREATE TABLE IF NOT EXISTS public.wholesale_pricing_rule_sets (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL UNIQUE,
  is_default BOOLEAN NOT NULL DEFAULT false,
  rules JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wholesale_pricing_rule_sets_default ON public.wholesale_pricing_rule_sets (is_default) WHERE is_default = true;

-- Import preview / apply audit
CREATE TABLE IF NOT EXISTS public.supplier_cost_import_runs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  admin_user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'preview',
  rules_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  csv_text TEXT NOT NULL,
  summary JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '48 hours'),
  applied_at TIMESTAMPTZ,
  CONSTRAINT supplier_cost_import_runs_status_check CHECK (status IN ('preview', 'applied', 'cancelled', 'expired'))
);

CREATE INDEX IF NOT EXISTS idx_supplier_cost_import_runs_created ON public.supplier_cost_import_runs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_supplier_cost_import_runs_status ON public.supplier_cost_import_runs (status);

CREATE TABLE IF NOT EXISTS public.supplier_cost_import_lines (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  run_id BIGINT NOT NULL REFERENCES public.supplier_cost_import_runs(id) ON DELETE CASCADE,
  line_no INT NOT NULL,
  sku TEXT NOT NULL,
  raw_row JSONB NOT NULL DEFAULT '{}'::jsonb,
  product_id BIGINT,
  status TEXT NOT NULL,
  source_cost NUMERIC(14,4),
  map_price NUMERIC(14,4),
  case_qty INT,
  brand TEXT,
  previous_cost NUMERIC(14,4),
  previous_price NUMERIC(14,4),
  previous_bulk_price NUMERIC(14,4),
  computed_price NUMERIC(14,4),
  computed_bulk_price NUMERIC(14,4),
  tier2_reference NUMERIC(14,4),
  tier3_reference NUMERIC(14,4),
  explain JSONB,
  warnings TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  error_message TEXT,
  CONSTRAINT supplier_cost_import_lines_status_check CHECK (status IN ('matched', 'unmatched', 'skipped', 'error', 'ambiguous_sku'))
);

CREATE INDEX IF NOT EXISTS idx_supplier_cost_import_lines_run ON public.supplier_cost_import_lines (run_id);
CREATE INDEX IF NOT EXISTS idx_supplier_cost_import_lines_sku ON public.supplier_cost_import_lines (sku);

COMMENT ON TABLE public.supplier_cost_import_runs IS 'Dry-run preview or applied supplier cost imports; lines hold per-SKU explainability.';
COMMENT ON TABLE public.wholesale_pricing_rule_sets IS 'Reusable wholesale pricing rule JSON for supplier cost imports.';

INSERT INTO public.wholesale_pricing_rule_sets (name, is_default, rules)
SELECT 'default',
  true,
  jsonb_build_object(
    'list_margin_percent', 45,
    'bulk_margin_percent', 35,
    'tier2_margin_percent', 38,
    'tier3_margin_percent', 40,
    'list_price_multiplier', NULL,
    'map_policy', 'floor_for_list',
    'min_price_floor_multiplier', 1,
    'map_applies_to_bulk', false,
    'update_case_qty_from_import', true,
    'update_brand_from_import', false,
    'merge_shipping_attributes', true
  )
WHERE NOT EXISTS (SELECT 1 FROM public.wholesale_pricing_rule_sets WHERE name = 'default');
