-- Bulk Import: jobs, items (queued -> done/error), product drafts (upsert by source_url), approve -> products

-- 1) import_jobs
CREATE TABLE IF NOT EXISTS import_jobs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  total_count INT NOT NULL DEFAULT 0
);

-- 2) import_job_items: one per URL; worker fills extracted_json, normalized_json; approve fills created_product_id
CREATE TABLE IF NOT EXISTS import_job_items (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  job_id BIGINT NOT NULL REFERENCES import_jobs(id) ON DELETE CASCADE,
  source_url TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'processing', 'done', 'error')),
  attempt_count INT NOT NULL DEFAULT 0,
  max_attempts INT NOT NULL DEFAULT 3,
  extracted_json JSONB,
  normalized_json JSONB,
  error_message TEXT,
  created_product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_import_job_items_job_id ON import_job_items(job_id);
CREATE INDEX IF NOT EXISTS idx_import_job_items_status ON import_job_items(status) WHERE status = 'queued';

-- 3) products_drafts: one per source_url (upsert by source_url); attributes populated, no price; status draft | approved
CREATE TABLE IF NOT EXISTS products_drafts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  source_url TEXT NOT NULL UNIQUE,
  import_job_item_id BIGINT REFERENCES import_job_items(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'approved')),
  sku TEXT,
  name TEXT,
  brand TEXT,
  description TEXT,
  image_url TEXT,
  images JSONB DEFAULT '[]'::jsonb,
  material TEXT,
  color TEXT,
  sizes TEXT,
  pack_qty INT,
  case_qty INT,
  category TEXT,
  subcategory TEXT,
  thickness TEXT,
  powder TEXT,
  grade TEXT,
  attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
  attribute_warnings TEXT[] DEFAULT '{}',
  source_confidence JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_products_drafts_status ON products_drafts(status);
CREATE INDEX IF NOT EXISTS idx_products_drafts_import_job_item ON products_drafts(import_job_item_id);
