-- CatalogOS: supplier feed ingestion, staging, matching, publish
-- Tenant-safe (tenant_id reserved for future use). All ingestion traceable by batch.

-- 1) suppliers
CREATE TABLE IF NOT EXISTS catalogos_suppliers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  settings JSONB NOT NULL DEFAULT '{}'::jsonb,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2) supplier_feeds (one supplier can have multiple feeds)
CREATE TABLE IF NOT EXISTS catalogos_supplier_feeds (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  supplier_id BIGINT NOT NULL REFERENCES catalogos_suppliers(id) ON DELETE CASCADE,
  feed_type TEXT NOT NULL CHECK (feed_type IN ('url', 'csv', 'api')),
  config JSONB NOT NULL DEFAULT '{}'::jsonb,
  schedule_cron TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_catalogos_supplier_feeds_supplier ON catalogos_supplier_feeds(supplier_id);

-- 3) import_batches (one per ingestion run)
CREATE TABLE IF NOT EXISTS catalogos_import_batches (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  feed_id BIGINT REFERENCES catalogos_supplier_feeds(id) ON DELETE SET NULL,
  supplier_id BIGINT NOT NULL REFERENCES catalogos_suppliers(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'completed', 'failed', 'cancelled')),
  started_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  stats JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_catalogos_import_batches_supplier ON catalogos_import_batches(supplier_id);
CREATE INDEX IF NOT EXISTS idx_catalogos_import_batches_status ON catalogos_import_batches(status);

-- 4) raw_supplier_products (immutable; never overwrite)
CREATE TABLE IF NOT EXISTS catalogos_raw_supplier_products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  batch_id BIGINT NOT NULL REFERENCES catalogos_import_batches(id) ON DELETE CASCADE,
  supplier_id BIGINT NOT NULL REFERENCES catalogos_suppliers(id) ON DELETE CASCADE,
  external_id TEXT NOT NULL,
  raw_json JSONB NOT NULL,
  checksum TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(batch_id, supplier_id, external_id)
);

CREATE INDEX IF NOT EXISTS idx_catalogos_raw_batch ON catalogos_raw_supplier_products(batch_id);
CREATE INDEX IF NOT EXISTS idx_catalogos_raw_supplier ON catalogos_raw_supplier_products(supplier_id);

-- 5) attribute_definitions (category-scoped attributes for normalization/matching)
CREATE TABLE IF NOT EXISTS catalogos_attribute_definitions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category TEXT NOT NULL,
  attribute_key TEXT NOT NULL,
  label TEXT NOT NULL,
  value_type TEXT NOT NULL DEFAULT 'string' CHECK (value_type IN ('string', 'number', 'boolean', 'string_array')),
  allowed_values JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(category, attribute_key)
);

CREATE INDEX IF NOT EXISTS idx_catalogos_attr_def_category ON catalogos_attribute_definitions(category);

-- 6) master_products (canonical catalog; publish syncs to products)
CREATE TABLE IF NOT EXISTS catalogos_master_products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  sku TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
  published_product_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_catalogos_master_category ON catalogos_master_products(category);
CREATE INDEX IF NOT EXISTS idx_catalogos_master_sku ON catalogos_master_products(sku);

-- 7) staging_products (normalized + attributes; link to master; review status)
CREATE TABLE IF NOT EXISTS catalogos_staging_products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  batch_id BIGINT NOT NULL REFERENCES catalogos_import_batches(id) ON DELETE CASCADE,
  raw_id BIGINT NOT NULL REFERENCES catalogos_raw_supplier_products(id) ON DELETE CASCADE,
  supplier_id BIGINT NOT NULL REFERENCES catalogos_suppliers(id) ON DELETE CASCADE,
  normalized_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  attributes_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  master_product_id BIGINT REFERENCES catalogos_master_products(id) ON DELETE SET NULL,
  match_confidence NUMERIC(5,4),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'merged')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_catalogos_staging_batch ON catalogos_staging_products(batch_id);
CREATE INDEX IF NOT EXISTS idx_catalogos_staging_status ON catalogos_staging_products(status);
CREATE INDEX IF NOT EXISTS idx_catalogos_staging_master ON catalogos_staging_products(master_product_id);

-- 8) supplier_offers (supplier + master + cost/lead time; source raw/staging)
CREATE TABLE IF NOT EXISTS catalogos_supplier_offers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  supplier_id BIGINT NOT NULL REFERENCES catalogos_suppliers(id) ON DELETE CASCADE,
  master_product_id BIGINT NOT NULL REFERENCES catalogos_master_products(id) ON DELETE CASCADE,
  supplier_sku TEXT NOT NULL,
  cost NUMERIC(12,4) NOT NULL,
  lead_time_days INT,
  raw_id BIGINT REFERENCES catalogos_raw_supplier_products(id) ON DELETE SET NULL,
  staging_id BIGINT REFERENCES catalogos_staging_products(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(supplier_id, master_product_id, supplier_sku)
);

CREATE INDEX IF NOT EXISTS idx_catalogos_offers_supplier ON catalogos_supplier_offers(supplier_id);
CREATE INDEX IF NOT EXISTS idx_catalogos_offers_master ON catalogos_supplier_offers(master_product_id);

-- 9) pricing_rules (margin/fixed by category, supplier, or product)
CREATE TABLE IF NOT EXISTS catalogos_pricing_rules (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  rule_type TEXT NOT NULL CHECK (rule_type IN ('default_margin', 'category_margin', 'supplier_margin', 'product_fixed')),
  scope_category TEXT,
  scope_supplier_id BIGINT REFERENCES catalogos_suppliers(id) ON DELETE CASCADE,
  scope_master_product_id BIGINT REFERENCES catalogos_master_products(id) ON DELETE CASCADE,
  margin_percent NUMERIC(8,4),
  fixed_price NUMERIC(12,4),
  priority INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_catalogos_pricing_scope ON catalogos_pricing_rules(rule_type);

-- 10) job_logs (per-batch step logs)
CREATE TABLE IF NOT EXISTS catalogos_job_logs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  batch_id BIGINT NOT NULL REFERENCES catalogos_import_batches(id) ON DELETE CASCADE,
  step TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('started', 'success', 'failed')),
  message TEXT,
  payload JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_catalogos_job_logs_batch ON catalogos_job_logs(batch_id);

-- 11) publish_log (audit: staging -> master, published_at, published_by)
CREATE TABLE IF NOT EXISTS catalogos_publish_log (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  staging_id BIGINT NOT NULL REFERENCES catalogos_staging_products(id) ON DELETE CASCADE,
  master_product_id BIGINT NOT NULL REFERENCES catalogos_master_products(id) ON DELETE CASCADE,
  published_product_id BIGINT,
  published_at TIMESTAMPTZ DEFAULT NOW(),
  published_by TEXT
);

CREATE INDEX IF NOT EXISTS idx_catalogos_publish_log_staging ON catalogos_publish_log(staging_id);
