-- Idempotent: products (minimal for pricing: sku, name, brand, cost, image_url, manufacturer_id)
CREATE TABLE IF NOT EXISTS products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  sku TEXT NOT NULL UNIQUE,
  name TEXT,
  brand TEXT,
  cost NUMERIC(12,2),
  image_url TEXT,
  manufacturer_id BIGINT REFERENCES manufacturers(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add manufacturer_id if products table already existed without it
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'manufacturer_id'
  ) THEN
    ALTER TABLE products ADD COLUMN manufacturer_id BIGINT REFERENCES manufacturers(id) ON DELETE SET NULL;
  END IF;
END $$;
