-- Canonical B2B pricing tiers + audit. Discount % is enforced only via commerce-pricing + users.discount_tier.

CREATE TABLE IF NOT EXISTS public.pricing_tiers (
  code TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  discount_percent NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (discount_percent >= 0 AND discount_percent <= 100),
  active BOOLEAN NOT NULL DEFAULT true,
  sort_priority INTEGER NOT NULL DEFAULT 0,
  require_is_approved BOOLEAN NOT NULL DEFAULT false,
  min_spend_ytd NUMERIC(14,2),
  min_spend_trailing_30 NUMERIC(14,2),
  min_spend_trailing_60 NUMERIC(14,2),
  min_spend_trailing_90 NUMERIC(14,2),
  min_spend_calendar_month NUMERIC(14,2),
  internal_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pricing_tiers_active_priority ON public.pricing_tiers (active, sort_priority DESC);

COMMENT ON TABLE public.pricing_tiers IS 'B2B tier definitions; first matching row by sort_priority wins. Null thresholds = no check.';
COMMENT ON COLUMN public.pricing_tiers.sort_priority IS 'Higher evaluated first; use high values for best tiers.';

CREATE TABLE IF NOT EXISTS public.pricing_tier_audit_log (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  old_tier_code TEXT,
  new_tier_code TEXT NOT NULL,
  reason TEXT,
  source TEXT NOT NULL,
  metrics_snapshot JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pricing_tier_audit_user ON public.pricing_tier_audit_log (user_id, created_at DESC);

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS pricing_tier_source TEXT NOT NULL DEFAULT 'manual';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'users_pricing_tier_source_check'
  ) THEN
    ALTER TABLE public.users
      ADD CONSTRAINT users_pricing_tier_source_check
      CHECK (pricing_tier_source IN ('auto', 'manual'));
  END IF;
END $$;

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS pricing_tier_evaluated_at TIMESTAMPTZ;

-- Existing accounts: manual preserves historical tier until an admin enables auto or runs evaluation.
UPDATE public.users SET pricing_tier_source = 'manual' WHERE pricing_tier_source IS NULL OR pricing_tier_source = '';

ALTER TABLE public.users ALTER COLUMN pricing_tier_source SET DEFAULT 'auto';

COMMENT ON COLUMN public.users.pricing_tier_source IS 'auto = server may change discount_tier from rules; manual = only admin/user PUT changes tier.';
COMMENT ON COLUMN public.users.pricing_tier_evaluated_at IS 'Last time automated tier evaluation ran for this user.';

INSERT INTO public.pricing_tiers (code, display_name, discount_percent, active, sort_priority, require_is_approved, min_spend_ytd, min_spend_trailing_30, min_spend_trailing_60, min_spend_trailing_90, min_spend_calendar_month, internal_notes)
VALUES
  ('platinum', 'Platinum', 20, true, 500, true, 50000, NULL, NULL, NULL, NULL, 'Legacy YTD threshold $50k+'),
  ('gold', 'Gold', 15, true, 400, true, 15000, NULL, NULL, NULL, NULL, 'Legacy YTD threshold $15k+'),
  ('silver', 'Silver', 10, true, 300, true, 5000, NULL, NULL, NULL, NULL, 'Legacy YTD threshold $5k+'),
  ('bronze', 'Bronze', 5, true, 200, true, 1000, NULL, NULL, NULL, NULL, 'Legacy YTD threshold $1k+'),
  ('standard', 'Standard', 0, true, 0, false, NULL, NULL, NULL, NULL, NULL, 'Fallback when no other tier qualifies')
ON CONFLICT (code) DO NOTHING;
