-- Lightweight outbound / early-customer pipeline (not a CRM).
-- Prospects are separate from quote requests (public.rfqs); link to companies when converted.

CREATE TABLE IF NOT EXISTS public.sales_prospects (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_name TEXT NOT NULL,
  contact_name TEXT,
  email TEXT,
  phone TEXT,
  source TEXT,
  status TEXT NOT NULL DEFAULT 'new',
  notes TEXT,
  converted_company_id BIGINT REFERENCES public.companies(id) ON DELETE SET NULL,
  created_by_admin_user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_contacted_at TIMESTAMPTZ,
  CONSTRAINT sales_prospects_status_check CHECK (
    status IN ('new', 'contacted', 'quoted', 'negotiating', 'won', 'lost', 'nurture')
  )
);

CREATE INDEX IF NOT EXISTS idx_sales_prospects_status ON public.sales_prospects (status);
CREATE INDEX IF NOT EXISTS idx_sales_prospects_created ON public.sales_prospects (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sales_prospects_email_lower ON public.sales_prospects (LOWER(email));

COMMENT ON TABLE public.sales_prospects IS 'Early-stage B2B leads; keep small-set workflows outside full CRM.';
