-- =============================================================================
-- GloveCubs: Inventory stock_reserved + stock_history for oversell prevention.
-- stock_on_hand = physical; stock_reserved = held by orders; available = on_hand - reserved
-- =============================================================================

-- Add quantity_reserved to inventory
ALTER TABLE public.inventory
  ADD COLUMN IF NOT EXISTS quantity_reserved INT NOT NULL DEFAULT 0;

-- Stock history for audit trail
CREATE TABLE IF NOT EXISTS public.stock_history (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  delta INT NOT NULL,
  type TEXT NOT NULL,
  reference_type TEXT,
  reference_id BIGINT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_stock_history_product ON public.stock_history (product_id);
CREATE INDEX IF NOT EXISTS idx_stock_history_created ON public.stock_history (created_at DESC);

-- Add received quantities to purchase_orders for partial receiving
ALTER TABLE public.purchase_orders
  ADD COLUMN IF NOT EXISTS received_lines JSONB DEFAULT '[]'::jsonb;
