-- AI telemetry and sku_recommendations (if not using recommendations table for same purpose)
-- ai_events: minimal event log for model calls (model_used, tokens_estimate, success, latency_ms)

CREATE TABLE IF NOT EXISTS ai_events (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  event_type TEXT NOT NULL,
  model_used TEXT NULL,
  tokens_estimate INT NULL,
  success BOOLEAN NOT NULL DEFAULT true,
  latency_ms INT NULL,
  meta JSONB NULL
);

CREATE INDEX IF NOT EXISTS idx_ai_events_created_at ON ai_events(created_at);
CREATE INDEX IF NOT EXISTS idx_ai_events_event_type ON ai_events(event_type);

-- sku_recommendations: per-request or per-line SKU recommendations with confidence (optional; recommendations table already exists)
CREATE TABLE IF NOT EXISTS sku_recommendations (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  upload_id BIGINT NULL REFERENCES invoice_uploads(id) ON DELETE SET NULL,
  conversation_id BIGINT NULL REFERENCES ai_conversations(id) ON DELETE SET NULL,
  line_index INT NULL,
  current_product TEXT NULL,
  recommended_sku TEXT NOT NULL,
  recommended_name TEXT NULL,
  brand TEXT NULL,
  estimated_savings NUMERIC(12,2) NULL,
  reason TEXT NULL,
  confidence NUMERIC(5,4) NULL,
  meta JSONB NULL
);

CREATE INDEX IF NOT EXISTS idx_sku_recommendations_upload_id ON sku_recommendations(upload_id);
CREATE INDEX IF NOT EXISTS idx_sku_recommendations_conversation_id ON sku_recommendations(conversation_id);
