-- Idempotent: manufacturers (for pricing overrides)
CREATE TABLE IF NOT EXISTS manufacturers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
